# Generated by Django 4.0.4 on 2022-06-30 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('tipovehiculo', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoAte',
            fields=[
                ('tipoate', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(default='imagen/defecto.jpg', null=True, upload_to='imagen')),
                ('publicar', models.BooleanField(default=False)),
                ('comentario', models.TextField()),
                ('usuario', models.CharField(default='--', max_length=60)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtaller.categoria')),
                ('tipoate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtaller.tipoate')),
            ],
        ),
    ]
