# Generated by Django 4.0.4 on 2022-06-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtaller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='imagen',
            field=models.ImageField(default='media/default.jpg', null=True, upload_to='productos'),
        ),
    ]
