# Generated by Django 4.0.4 on 2022-07-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtaller', '0004_alter_atencion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='usuario',
            field=models.CharField(default='{{user.username}}', max_length=60),
        ),
    ]
