# Generated by Django 4.0.4 on 2022-07-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtaller', '0005_alter_atencion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='usuario',
            field=models.CharField(default='--', max_length=60),
        ),
    ]
