# Generated by Django 4.0.4 on 2022-07-13 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtaller', '0006_alter_atencion_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtaller.atencion')),
            ],
        ),
    ]
