# Generated by Django 4.0.4 on 2022-07-13 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtaller', '0007_imagenatencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenatencion',
            name='atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='webtaller.atencion'),
        ),
    ]
